name: main
on: push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the main branch
      uses: actions/checkout@v3
      with:
        ref: main
    - name: Capture the screenshot
      run: |
        # Print commands as they are executed
        set -x

        # Configure GitHub Actions service account Git identity
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

        # Configure `git filter-branch` to not complain and just do the job
        export FILTER_BRANCH_SQUELCH_WARNING=1

        # Wipe existing screenshot from the history
        git filter-branch --index-filter "git rm --cached --ignore-unmatch screencast-linux.apng" --prune-empty HEAD

        # Install Node dependencies
        npm install

        # Compile the extension
        npm run compile

        # Run the test which generates the screenshot
        export DISPLAY=":0"
        xvfb-run --auto-servernum node ./out/test/runTest.js

        # Stage the captured screenshot
        git add screencast-linux.apng

        # Reset unstaged changes so that Git commit won't fail (e.g.: package-lock.json, temporary files, …)
        git checkout -- .

        # Commit the staged changes to the workflow repository
        git commit -m "Commit CI Linux screencast" -m "This commit was generated by the GitHub Actions workflow."

        # Push the generated data to GitHub (force because of the filter-branch)
        git push --force
